### ISSUE TITLE
JOSE paper - references

### ISSUE THREAD

**Issue by e-dub** [mbarzegary/educational-bayesian#12]
Three references is a bit "thin" to me.  Is this the complete list of references?  An open question is if the references of your original code should also be included here.

**Comment by mbarzegary** [comment]
You are right, the number of references is too small, but I wrote that based on the average number of references I had seen in JOSE papers. So, I added 4 more relevant scientific papers to the text. I removed the reference to the original code to address issue #6, and it’s not applicable to cite it anymore.
