### ISSUE TITLE
Target audience

### ISSUE THREAD

**Issue by e-dub** [mbarzegary/educational-bayesian#3]
According to the review checklist the need and target audience must be stated.  Maybe you could state level, general field(s) and learning objectives.

**Comment by mbarzegary** [comment]
Thanks. The proper text was added to address this.

**Comment by e-dub** [comment]
I find that the sentence added "The provided material is the format of a crash course, which is suitable for being taught in one session of undergraduate or graduate courses for science and engineering students." is not specific enough. See your example.
