### ISSUE TITLE
Goal of publication

### ISSUE THREAD

**Issue by e-dub** [mbarzegary/educational-bayesian#6]
The goal of the publication is not fully clear to me.  The original source code seems to be "just" an add-on. Am I correct in seeing that this submission is for the accompanying iPython code? I.e. the documentation?  Should this be part of the original code repository?

**Comment by mbarzegary** [comment]
That’s very correct. Indeed, including the main source code, out of which this module is created, is not necessary as not only does it bring some ambiguity (similar to what you have mentioned), but also it makes redundancy in the codes. The main focus of the repository and the module is on education, so the original code is removed, and the educational modules were moved to the src directory. It makes the primary purpose of the module clear that it’s not documentation of the original code. The original code will not be referenced here at all as the students are able to reconstruct it from the notebook after learning the whole process.
