### ISSUE TITLE
JOSE paper - Typos, grammar, etc

### ISSUE THREAD

**Issue by e-dub** [mbarzegary/educational-bayesian#9]
Several smaller errors need to be corrected, e.g. 

wrong usage of inevitable
are ~~the~~ models derived
according to ~~(~~ Tarantol (1987), 
measurements of ~~the~~ observable parameters
one solution is TO solve

Please reread and correct, if possible by another English speaker.

**Comment by mbarzegary** [comment]
Thank you for pointing this out. The text was reread and corrected again, and several mistakes were fixed.

**Comment by e-dub** [comment]
There are still errors. E.g. 𝑝(score|parameters 

Explain all nomenclature fully. This is not done.

Add references where necessary. 

I find the writing difficult to follow.
